git:
    depth: 1

language: haxe

notifications:
  email:
    on_success: never
    on_failure: never

haxe:
  - "3.4.7"

script:
  - haxe macro-test-runner.hxml && neko macro_test/test_runner.n
  - haxe test.hxml
