git:
    depth: 1

language: haxe

notifications:
  email:
    on_success: never
    on_failure: never

haxe:
  - "4.1.4"

script:
  - haxelib install hx3compat
  - haxe macro-test-runner.hxml && neko macro_test/test_runner.n
  - haxe test.hxml
